import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<string, Record<Language, string>> = {
  "Dashboard": { en: "Dashboard", ar: "لوحة التحكم" },
  "Appointment Requests": { en: "Appointment Requests", ar: "طلبات المواعيد" },
  "International Patients": { en: "International Patients", ar: "المرضى الدوليون" },
  "Feedback & Reviews": { en: "Feedback & Reviews", ar: "الملاحظات والتقييمات" },
  "Doctors": { en: "Doctors", ar: "الأطباء" },
  "Departments": { en: "Departments", ar: "الأقسام" },
  "Categories": { en: "Categories", ar: "التصنيفات" },
  "Manage hospital categories used when creating departments.": {
    en: "Manage hospital categories used when creating departments.",
    ar: "إدارة تصنيفات المستشفى المستخدمة عند إنشاء الأقسام.",
  },
  "Add category": { en: "Add category", ar: "إضافة تصنيف" },
  "Search categories...": { en: "Search categories...", ar: "بحث في التصنيفات..." },
  "Category created successfully": { en: "Category created successfully", ar: "تم إنشاء التصنيف بنجاح" },
  "Category updated successfully": { en: "Category updated successfully", ar: "تم تحديث التصنيف بنجاح" },
  "Category deleted successfully": { en: "Category deleted successfully", ar: "تم حذف التصنيف بنجاح" },
  "Failed to save": { en: "Failed to save", ar: "فشل الحفظ" },
  "Failed to delete": { en: "Failed to delete", ar: "فشل الحذف" },
  "Edit category": { en: "Edit category", ar: "تعديل التصنيف" },
  "Delete category": { en: "Delete category", ar: "حذف التصنيف" },
  "Delete category confirm": { en: "Are you sure you want to delete", ar: "هل أنت متأكد أنك تريد حذف" },
  "Category name": { en: "Category name", ar: "اسم التصنيف" },
  "Subspecialities": { en: "Subspecialities", ar: "التخصصات الفرعية" },
  "Manage hospital subspecialities used when creating departments.": {
    en: "Manage hospital subspecialities used when creating departments.",
    ar: "إدارة التخصصات الفرعية المستخدمة عند إنشاء الأقسام.",
  },
  "Add subspeciality": { en: "Add subspeciality", ar: "إضافة تخصص فرعي" },
  "Search subspecialities...": { en: "Search subspecialities...", ar: "بحث في التخصصات الفرعية..." },
  "Subspeciality created successfully": {
    en: "Subspeciality created successfully",
    ar: "تم إنشاء التخصص الفرعي بنجاح",
  },
  "Subspeciality updated successfully": {
    en: "Subspeciality updated successfully",
    ar: "تم تحديث التخصص الفرعي بنجاح",
  },
  "Subspeciality deleted successfully": {
    en: "Subspeciality deleted successfully",
    ar: "تم حذف التخصص الفرعي بنجاح",
  },
  "Edit subspeciality": { en: "Edit subspeciality", ar: "تعديل التخصص الفرعي" },
  "Delete subspeciality": { en: "Delete subspeciality", ar: "حذف التخصص الفرعي" },
  "Delete subspeciality confirm": {
    en: "Are you sure you want to delete",
    ar: "هل أنت متأكد أنك تريد حذف",
  },
  "Subspeciality name": { en: "Subspeciality name", ar: "اسم التخصص الفرعي" },
  "Subspeciality description": {
    en: "Subspeciality description",
    ar: "وصف التخصص الفرعي",
  },
  "Description is required": { en: "Description is required", ar: "الوصف مطلوب" },
  "Name is required": { en: "Name is required", ar: "الاسم مطلوب" },
  "Hospitality Services": { en: "Hospitality Services", ar: "خدمات الضيافة" },
  "Documents": { en: "Documents", ar: "المستندات" },
  "Reports": { en: "Reports", ar: "التقارير" },
  "Settings": { en: "Settings", ar: "الإعدادات" },
  "Admin": { en: "Admin", ar: "المسؤول" },
  "Secure Logout": { en: "Secure Logout", ar: "تسجيل خروج آمن" },
  "Notifications": { en: "Notifications", ar: "الإشعارات" },
  "Search...": { en: "Search...", ar: "بحث..." },
  "Mark all read": { en: "Mark all read", ar: "تحديد الكل كمقروء" },
  "Total Appointments": { en: "Total Appointments", ar: "إجمالي المواعيد" },
  "Pending Requests": { en: "Pending Requests", ar: "الطلبات المعلقة" },
  "Confirmed Today": { en: "Confirmed Today", ar: "مؤكد اليوم" },
  "Cancelled": { en: "Cancelled", ar: "ملغاة" },
  "Doctors Available": { en: "Doctors Available", ar: "أطباء متاحون" },
  "International Enquiries": { en: "International Enquiries", ar: "استفسارات دولية" },
  "Documents Uploaded": { en: "Documents Uploaded", ar: "مستندات محملة" },
  "Weekly Appointments": { en: "Weekly Appointments", ar: "المواعيد الأسبوعية" },
  "Monthly Trends": { en: "Monthly Trends", ar: "الاتجاهات الشهرية" },
  "Avg Rating": { en: "Avg Rating", ar: "متوسط التقييم" },
  "Feedback Count": { en: "Feedback Count", ar: "عدد الملاحظات" },
  "Sun": { en: "Sun", ar: "أحد" }, "Mon": { en: "Mon", ar: "إثن" }, "Tue": { en: "Tue", ar: "ثلا" },
  "Wed": { en: "Wed", ar: "أربع" }, "Thu": { en: "Thu", ar: "خميس" }, "Fri": { en: "Fri", ar: "جمعة" }, "Sat": { en: "Sat", ar: "سبت" },
  "Back": { en: "Back", ar: "رجوع" }, "Close": { en: "Close", ar: "إغلاق" }, "Submit": { en: "Submit", ar: "إرسال" },
  "Save": { en: "Save", ar: "حفظ" }, "Cancel": { en: "Cancel", ar: "إلغاء" }, "Edit": { en: "Edit", ar: "تعديل" },
  "Delete": { en: "Delete", ar: "حذف" }, "Search": { en: "Search", ar: "بحث" }, "Export": { en: "Export", ar: "تصدير" },
  "Download": { en: "Download", ar: "تحميل" }, "Upload": { en: "Upload", ar: "رفع" }, "View All": { en: "View All", ar: "عرض الكل" },
  "All": { en: "All", ar: "الكل" }, "Active": { en: "Active", ar: "نشط" }, "Inactive": { en: "Inactive", ar: "غير نشط" },
  "Pending": { en: "Pending", ar: "قيد الانتظار" }, "Confirmed": { en: "Confirmed", ar: "مؤكد" },
  "Completed": { en: "Completed", ar: "مكتمل" }, "Rescheduled": { en: "Rescheduled", ar: "أعيد جدولته" },
  "Name": { en: "Name", ar: "الاسم" }, "Description": { en: "Description", ar: "الوصف" },
  "Notes": { en: "Notes", ar: "ملاحظات" }, "Status": { en: "Status", ar: "الحالة" },
  "Date": { en: "Date", ar: "التاريخ" }, "Type": { en: "Type", ar: "النوع" },
  "Phone": { en: "Phone", ar: "الهاتف" }, "Email": { en: "Email", ar: "البريد الإلكتروني" },
  "Total": { en: "Total", ar: "المجموع" }, "Loading...": { en: "Loading...", ar: "جاري التحميل..." },
  "No data available": { en: "No data available", ar: "لا توجد بيانات" },
  "Yes": { en: "Yes", ar: "نعم" }, "No": { en: "No", ar: "لا" },
  "Head of Dept": { en: "Head of Dept", ar: "رئيس القسم" }, "Location": { en: "Location", ar: "الموقع" },
  "Total Patients": { en: "Total Patients", ar: "إجمالي المرضى" }, "Beds": { en: "Beds", ar: "الأسرة" },
  "Operating Hours": { en: "Operating Hours", ar: "ساعات العمل" }, "Equipment": { en: "Equipment", ar: "المعدات" },
  "Specialties": { en: "Specialties", ar: "التخصصات" }, "Services": { en: "Services", ar: "الخدمات" },
  "Assigned Doctors": { en: "Assigned Doctors", ar: "الأطباء المعينون" },
  "Available": { en: "Available", ar: "متاح" }, "Unavailable": { en: "Unavailable", ar: "غير متاح" },
  "Treatment": { en: "Treatment", ar: "العلاج" }, "Source": { en: "Source", ar: "المصدر" },
  "Message": { en: "Message", ar: "الرسالة" }, "Enquiry Date": { en: "Enquiry Date", ar: "تاريخ الاستفسار" },
  "New Enquiries": { en: "New Enquiries", ar: "استفسارات جديدة" }, "Contacted": { en: "Contacted", ar: "تم الاتصال" },
  "Scheduled": { en: "Scheduled", ar: "مجدول" }, "Closed": { en: "Closed", ar: "مغلق" },
  "Related Area": { en: "Related Area", ar: "المنطقة ذات الصلة" },
  "Usage": { en: "Usage", ar: "الاستخدام" }, "Contact Person": { en: "Contact Person", ar: "الشخص المسؤول" },
  "Availability": { en: "Availability", ar: "التوفر" }, "Last Updated": { en: "Last Updated", ar: "آخر تحديث" },
  "Features": { en: "Features", ar: "المميزات" }, "Operational Notes": { en: "Operational Notes", ar: "ملاحظات تشغيلية" },
  "Upload Document": { en: "Upload Document", ar: "رفع مستند" }, "Document Title": { en: "Document Title", ar: "عنوان المستند" },
  "Category": { en: "Category", ar: "الفئة" }, "Share": { en: "Share", ar: "مشاركة" },
  "Share Document": { en: "Share Document", ar: "مشاركة المستند" },
  "Send via SMS": { en: "Send via SMS", ar: "إرسال عبر رسالة نصية" },
  "Send document link to patient's phone": { en: "Send document link to patient's phone", ar: "إرسال رابط المستند إلى هاتف المريض" },
  "Send via WhatsApp": { en: "Send via WhatsApp", ar: "إرسال عبر واتساب" },
  "Share through WhatsApp message": { en: "Share through WhatsApp message", ar: "مشاركة عبر رسالة واتساب" },
  "Generate QR Code": { en: "Generate QR Code", ar: "إنشاء رمز QR" },
  "Create scannable QR code for this document": { en: "Create scannable QR code for this document", ar: "إنشاء رمز QR قابل للمسح لهذا المستند" },
  "Copy Link": { en: "Copy Link", ar: "نسخ الرابط" },
  "Copy document link to clipboard": { en: "Copy document link to clipboard", ar: "نسخ رابط المستند إلى الحافظة" },
  "Shared": { en: "Shared", ar: "تمت المشاركة" }, "times": { en: "times", ar: "مرات" },
  "documents": { en: "documents", ar: "مستندات" },
  "Upload and manage documents to share with patients via SMS, WhatsApp, or QR code.": { en: "Upload and manage documents to share with patients via SMS, WhatsApp, or QR code.", ar: "رفع وإدارة المستندات لمشاركتها مع المرضى عبر الرسائل النصية أو واتساب أو رمز QR." },
  "Feedback Trends": { en: "Feedback Trends", ar: "اتجاهات الملاحظات" },
  "By Rating": { en: "By Rating", ar: "حسب التقييم" }, "By Status": { en: "By Status", ar: "حسب الحالة" },
  "Average Rating Trend": { en: "Average Rating Trend", ar: "اتجاه متوسط التقييم" },
  "Request Volume & Conversions": { en: "Request Volume & Conversions", ar: "حجم الطلبات والتحويلات" },
  "Request Status": { en: "Request Status", ar: "حالة الطلب" },
  "Conversion Rate": { en: "Conversion Rate", ar: "معدل التحويل" },
  "By Source": { en: "By Source", ar: "حسب المصدر" },
  "Requests": { en: "Requests", ar: "الطلبات" }, "Converted": { en: "Converted", ar: "محولة" },
  "Rejected": { en: "Rejected", ar: "مرفوض" },
  "Enquiries by Country": { en: "Enquiries by Country", ar: "الاستفسارات حسب البلد" },
  "Monthly Enquiry Trends": { en: "Monthly Enquiry Trends", ar: "اتجاهات الاستفسارات الشهرية" },
  "New": { en: "New", ar: "جديد" }, "Replied": { en: "Replied", ar: "تم الرد" },
  "Flagged": { en: "Flagged", ar: "مميز" }, "Resolved": { en: "Resolved", ar: "محلول" },
  "Rating": { en: "Rating", ar: "التقييم" }, "Comment": { en: "Comment", ar: "التعليق" },
  "Response": { en: "Response", ar: "الرد" }, "Respond": { en: "Respond", ar: "الرد" },
  "Patient": { en: "Patient", ar: "المريض" }, "Doctor": { en: "Doctor", ar: "الطبيب" },
  "Department": { en: "Department", ar: "القسم" },
  "Doctor Profile": { en: "Doctor Profile", ar: "ملف الطبيب" },
  "Specialty": { en: "Specialty", ar: "التخصص" }, "Edit Profile": { en: "Edit Profile", ar: "تعديل الملف" },
  "Languages": { en: "Languages", ar: "اللغات" }, "Experience": { en: "Experience", ar: "الخبرة" },
  "Qualifications": { en: "Qualifications", ar: "المؤهلات" },
  "General": { en: "General", ar: "عام" }, "Security": { en: "Security", ar: "الأمان" },
  "Language Settings": { en: "Language Settings", ar: "إعدادات اللغة" },
  "Notification Settings": { en: "Notification Settings", ar: "إعدادات الإشعارات" },
  "Login": { en: "Login", ar: "تسجيل الدخول" }, "Username": { en: "Username", ar: "اسم المستخدم" },
  "Password": { en: "Password", ar: "كلمة المرور" }, "Sign In": { en: "Sign In", ar: "تسجيل الدخول" },
  "Medical Records Requests": { en: "Medical Records Requests", ar: "طلبات السجلات الطبية" },
  "Al Safwa Enrollments": { en: "Al Safwa Enrollments", ar: "تسجيلات الصفوة" },
  "Contact Messages": { en: "Contact Messages", ar: "رسائل التواصل" },
  "Job Applications": { en: "Job Applications", ar: "طلبات التوظيف" },
  "Manage patient requests for medical records submitted via the website Quick Links form.": { en: "Manage patient requests for medical records submitted via the website Quick Links form.", ar: "إدارة طلبات المرضى للسجلات الطبية المقدمة عبر نموذج الروابط السريعة في الموقع." },
  "Manage enrollment applications for the Al Safwa Healthcare Program submitted via the website.": { en: "Manage enrollment applications for the Al Safwa Healthcare Program submitted via the website.", ar: "إدارة طلبات التسجيل في برنامج الصفوة الصحي المقدمة عبر الموقع." },
  "Messages received from the Contact Us form on the website.": { en: "Messages received from the Contact Us form on the website.", ar: "الرسائل المستلمة من نموذج اتصل بنا في الموقع." },
  "Applications received from the Work With Us section of the website.": { en: "Applications received from the Work With Us section of the website.", ar: "الطلبات المستلمة من قسم اعمل معنا في الموقع." },
  "Search by name or ID...": { en: "Search by name or ID...", ar: "بحث بالاسم أو الرقم..." },
  "Search by name or subject...": { en: "Search by name or subject...", ar: "بحث بالاسم أو الموضوع..." },
  "Search by name or position...": { en: "Search by name or position...", ar: "بحث بالاسم أو المنصب..." },
  "Request ID": { en: "Request ID", ar: "رقم الطلب" }, "Record Type": { en: "Record Type", ar: "نوع السجل" },
  "Purpose": { en: "Purpose", ar: "الغرض" }, "Approve": { en: "Approve", ar: "موافقة" },
  "Approved": { en: "Approved", ar: "موافق عليه" }, "Reject": { en: "Reject", ar: "رفض" },
  "Patient ID": { en: "Patient ID", ar: "رقم المريض" }, "Applicant": { en: "Applicant", ar: "المتقدم" },
  "Plan": { en: "Plan", ar: "الخطة" }, "Members": { en: "Members", ar: "الأعضاء" },
  "Nationality": { en: "Nationality", ar: "الجنسية" }, "Date of Birth": { en: "Date of Birth", ar: "تاريخ الميلاد" },
  "Al Safwa Enrollment": { en: "Al Safwa Enrollment", ar: "تسجيل الصفوة" },
  "Sender": { en: "Sender", ar: "المرسل" }, "Subject": { en: "Subject", ar: "الموضوع" },
  "Reply": { en: "Reply", ar: "رد" }, "Position": { en: "Position", ar: "المنصب" },
  "Cover Letter": { en: "Cover Letter", ar: "خطاب التقديم" },
  "Download CV": { en: "Download CV", ar: "تحميل السيرة الذاتية" },
  "Shortlist": { en: "Shortlist", ar: "قائمة مختصرة" }, "Shortlisted": { en: "Shortlisted", ar: "في القائمة المختصرة" },
  "Interview": { en: "Interview", ar: "مقابلة" }, "Job Application": { en: "Job Application", ar: "طلب توظيف" },
  "ID": { en: "ID", ar: "الرقم" }, "Actions": { en: "Actions", ar: "الإجراءات" },
  "Personal Details": { en: "Personal Details", ar: "البيانات الشخصية" },
  "Professional Details": { en: "Professional Details", ar: "البيانات المهنية" },
  "Applied": { en: "Applied", ar: "تقدم بتاريخ" },
  "Gender": { en: "Gender", ar: "الجنس" },
  "Address": { en: "Address", ar: "العنوان" },
  "Visa Status": { en: "Visa Status", ar: "حالة التأشيرة" },
  "Education": { en: "Education", ar: "التعليم" },
  "Certifications": { en: "Certifications", ar: "الشهادات" },
  "References": { en: "References", ar: "المراجع" },
  "Schedule Interview": { en: "Schedule Interview", ar: "جدولة مقابلة" },
  "Profile Details": { en: "Profile Details", ar: "تفاصيل الملف" },
  "Bio": { en: "Bio", ar: "السيرة" },
  "Current Work": { en: "Current Work", ar: "العمل الحالي" },
  "Expertise": { en: "Expertise", ar: "الخبرات" },
  "Statistics": { en: "Statistics", ar: "الإحصائيات" },
  "Controls": { en: "Controls", ar: "عناصر التحكم" },
  "Online Booking": { en: "Online Booking", ar: "الحجز عبر الإنترنت" },
  "Website Visibility": { en: "Website Visibility", ar: "الظهور على الموقع" },
  "Open": { en: "Open", ar: "مفتوح" },
  "Photos": { en: "Photos", ar: "الصور" },
  "Add Photo": { en: "Add Photo", ar: "إضافة صورة" },
  "Booking Open": { en: "Booking Open", ar: "الحجز مفتوح" },
  "Booking Closed": { en: "Booking Closed", ar: "الحجز مغلق" },
  "Visible": { en: "Visible", ar: "ظاهر" },
  "Hidden": { en: "Hidden", ar: "مخفي" },
  "years experience": { en: "years experience", ar: "سنوات خبرة" },
  "Next Available": { en: "Next Available", ar: "التالي المتاح" },
  "Online Appointments": { en: "Online Appointments", ar: "المواعيد عبر الإنترنت" },
  "Joined Date": { en: "Joined Date", ar: "تاريخ الانضمام" },
  "Joined": { en: "Joined", ar: "انضم" },
  "Online Appts": { en: "Online Appts", ar: "مواعيد إلكترونية" },
  "Add": { en: "Add", ar: "إضافة" },
  "Click to hide department": { en: "Click to hide department", ar: "انقر لإخفاء القسم" },
  "Click to show department": { en: "Click to show department", ar: "انقر لإظهار القسم" },
  "Patient Phone Number": { en: "Patient Phone Number", ar: "رقم هاتف المريض" },
  "Send": { en: "Send", ar: "إرسال" },
  "Sent successfully!": { en: "Sent successfully!", ar: "تم الإرسال بنجاح!" },
  "Scan to access document": { en: "Scan to access document", ar: "امسح للوصول إلى المستند" },
  "Patient Email": { en: "Patient Email", ar: "بريد المريض" },
  "optional": { en: "optional", ar: "اختياري" },
  "Download QR": { en: "Download QR", ar: "تحميل QR" },
  "Send link to email": { en: "Send link to email", ar: "إرسال الرابط عبر البريد" },
  "Forward to Department": { en: "Forward to Department", ar: "إعادة توجيه إلى القسم" },
  "Select Department": { en: "Select Department", ar: "اختر القسم" },
  "Reply Message": { en: "Reply Message", ar: "رسالة الرد" },
  "Type your reply...": { en: "Type your reply...", ar: "اكتب ردك..." },
  "Send Reply": { en: "Send Reply", ar: "إرسال الرد" },
  "Reply sent and forwarded to department": { en: "Reply sent and forwarded to department", ar: "تم إرسال الرد وإعادة توجيهه إلى القسم" },
  "Weekly Requests & Conversions": { en: "Weekly Requests & Conversions", ar: "الطلبات والتحويلات الأسبوعية" },
  "Request Sources": { en: "Request Sources", ar: "مصادر الطلبات" },
  "Feedback by Rating": { en: "Feedback by Rating", ar: "الملاحظات حسب التقييم" },
  "Department Patient Load": { en: "Department Patient Load", ar: "حمل المرضى حسب القسم" },
  "Online": { en: "Online", ar: "إلكتروني" },
  "Walk-in": { en: "Walk-in", ar: "حضور مباشر" },
  "International": { en: "International", ar: "دولي" },
  "Confirm Appointment": { en: "Confirm Appointment", ar: "تأكيد الموعد" },
  "Has the confirmation been given by the doctor and department?": { en: "Has the confirmation been given by the doctor and department?", ar: "هل تم الحصول على التأكيد من الطبيب والقسم؟" },
  "Confirmed by Doctor": { en: "Confirmed by Doctor", ar: "مؤكد من الطبيب" },
  "Confirm & Convert": { en: "Confirm & Convert", ar: "تأكيد وتحويل" },
  "Convert to Appointment": { en: "Convert to Appointment", ar: "تحويل إلى موعد" },
  "Assign Doctor": { en: "Assign Doctor", ar: "تعيين طبيب" },
  "Request Info": { en: "Request Info", ar: "طلب معلومات" },
  "Select Doctor": { en: "Select Doctor", ar: "اختر طبيب" },
  "Doctor Unavailable": { en: "Doctor Unavailable", ar: "الطبيب غير متاح" },
  "Request Confirmation": { en: "Request Confirmation", ar: "طلب تأكيد" },
  "currently has online booking": { en: "currently has online booking", ar: "حالياً حجزه الإلكتروني" },
  "Would you like to request confirmation from the doctor before assigning?": { en: "Would you like to request confirmation from the doctor before assigning?", ar: "هل تريد طلب تأكيد من الطبيب قبل التعيين؟" },
  "Doctor Preference": { en: "Doctor Preference", ar: "الطبيب المفضل" },
  "Language": { en: "Language", ar: "اللغة" },
  "Insurance": { en: "Insurance", ar: "التأمين" },
  "Records Uploaded": { en: "Records Uploaded", ar: "السجلات المرفوعة" },
  "Patient Type": { en: "Patient Type", ar: "نوع المريض" },
  "Request Date": { en: "Request Date", ar: "تاريخ الطلب" },
  "Symptoms / Reason": { en: "Symptoms / Reason", ar: "الأعراض / السبب" },
  "Available Doctors in": { en: "Available Doctors in", ar: "الأطباء المتاحون في" },
  "Next": { en: "Next", ar: "التالي" },
  "Request History": { en: "Request History", ar: "سجل الطلب" },
  "Awaiting": { en: "Awaiting", ar: "في الانتظار" },
  "urgent": { en: "Urgent", ar: "عاجل" },
  "normal": { en: "Normal", ar: "عادي" },
  "routine": { en: "Routine", ar: "روتيني" },
  "new": { en: "New", ar: "جديد" },
  "converted": { en: "Converted", ar: "محول" },
  "pending_info": { en: "Pending Info", ar: "بانتظار معلومات" },
  "awaiting_confirmation": { en: "Awaiting Confirmation", ar: "بانتظار التأكيد" },
  "awaiting confirmation": { en: "Awaiting Confirmation", ar: "بانتظار التأكيد" },
  "pending info": { en: "Pending Info", ar: "بانتظار معلومات" },
  "Pricing": { en: "Pricing", ar: "التسعير" },
  "Last 1 Month": { en: "Last 1 Month", ar: "آخر شهر" },
  "Last 3 Months": { en: "Last 3 Months", ar: "آخر 3 أشهر" },
  "Last 6 Months": { en: "Last 6 Months", ar: "آخر 6 أشهر" },
  "Last 1 Year": { en: "Last 1 Year", ar: "آخر سنة" },
  "Feedback": { en: "Feedback", ar: "ملاحظات" },
  "CSR Initiatives": { en: "CSR Initiatives", ar: "مبادرات المسؤولية الاجتماعية" },
  "Work Culture": { en: "Work Culture", ar: "ثقافة العمل" },
  "Leadership Team": { en: "Leadership Team", ar: "فريق القيادة" },
  "Life at RHH": { en: "Life at RHH", ar: "الحياة في آر إتش إتش" },
  "View Details": { en: "View Details", ar: "عرض التفاصيل" },
  "Create New": { en: "Create New", ar: "إنشاء جديد" },
  "Add CSR Initiative": { en: "Add CSR Initiative", ar: "إضافة مبادرة" },
  "View CSR Initiative": { en: "View CSR Initiative", ar: "عرض المبادرة" },
  "Edit CSR Initiative": { en: "Edit CSR Initiative", ar: "تعديل المبادرة" },
  "Add Work Culture Event": { en: "Add Work Culture Event", ar: "إضافة حدث ثقافة العمل" },
  "View Work Culture": { en: "View Work Culture", ar: "عرض ثقافة العمل" },
  "Edit Work Culture": { en: "Edit Work Culture", ar: "تعديل ثقافة العمل" },
  "Add Leadership Member": { en: "Add Leadership Member", ar: "إضافة عضو قيادة" },
  "View Leadership": { en: "View Leadership", ar: "عرض القيادي" },
  "Edit Leadership": { en: "Edit Leadership", ar: "تعديل القيادي" },
  "Manage CSR initiatives and Celebrating Life content": {
    en: "Manage CSR initiatives and Celebrating Life content",
    ar: "إدارة مبادرات المسؤولية الاجتماعية ومحتوى الاحتفال بالحياة",
  },
  "Manage work culture events and Life at RHH content": {
    en: "Manage work culture events and Life at RHH content",
    ar: "إدارة أحداث ثقافة العمل ومحتوى الحياة في آر إتش إتش",
  },
  "Manage leadership team members": {
    en: "Manage leadership team members",
    ar: "إدارة أعضاء فريق القيادة",
  },
  "Process and manage Al Safwa program enrollments": {
    en: "Process and manage Al Safwa program enrollments",
    ar: "معالجة وإدارة تسجيلات برنامج الصفوة",
  },
  "Home": { en: "Home", ar: "الرئيسية" },
  "Pages": { en: "Pages", ar: "الصفحات" },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem("rhh_lang") as Language) || "en";
  });

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("rhh_lang", l);
  };

  const isRTL = lang === "ar";

  useEffect(() => {
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, [lang, isRTL]);

  const t = (key: string): string => {
    return translations[key]?.[lang] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
